### ISSUE TITLE
Suggestion: use httpx status code methods and descriptions

### ISSUE THREAD

**Issue by dolamroth** [DmitryBurnaev/podcast-service#200]
Instead of https://github.com/DmitryBurnaev/podcast-service/blob/12caa21a69c55fdc523dd23ef2a7c9a8d8937b6f/src/common/utils.py#L33

Use `httpx.codes.is_error(...)`

Instead of https://github.com/DmitryBurnaev/podcast-service/blob/efd4578f17fb9623c7267d1d8c9bac01686d8d12/src/common/statuses.py

Use `httpx.codes.%something%.name/value`

**Comment by DmitryBurnaev** [comment]
Thanks! I've created PR https://github.com/DmitryBurnaev/podcast-service/pull/203
